name: tubes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Networking & Data
  http: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0

  # UI & Assets
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Pastikan file gambar kamu ada di folder lib/assets/
  assets:
    - lib/assets/

    